project:
  type: book
  output-dir: docs


book:
  title: "R: The Fundamentals"
  navbar:
    title: "mb-data"
    left:
      - text: Home
        href: /index.html
      - text: About
        file: /about.html
      - text: "Tutorials"
        #file: tutorials.qmd
        menu:
          - text: "R: The Fundamentals"
            href: index.qmd
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-setup.qmd
    - 03-interacting.qmd
    - further.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo



